export = Source;
declare class Source {
    static resolve(input: string, weak?: boolean): null | Promise<ReturnType<typeof apple.resolve> | ReturnType<typeof soundcloud.resolve> | ReturnType<typeof soundcloud.resolve> | ReturnType<typeof youtube.resolve> | ReturnType<typeof file.api.create>>;
}
declare namespace Source {
    export { SourceError as Error };
    export { youtube as Youtube };
    export { soundcloud as Soundcloud };
    export { spotify as Spotify };
    export { apple as AppleMusic };
    export { file as File };
}
declare var apple: AppleMusic;
declare var soundcloud: Soundcloud;
declare var youtube: Youtube;
declare var file: File;
import SourceError = require("./SourceError");
declare var spotify: Spotify;
declare class AppleMusic extends APISource<"AppleMusic"> {
    constructor();
    override match(content: string): null | {
        track: string;
    } | {
        album: string;
    } | {
        playlist: string;
    };
    resolve(match: ReturnType<typeof this.match>): Promise<import('./api/AppleMusic').Track | import('./api/AppleMusic').Playlist | undefined>;
    search(query: string, offset?: number | undefined, length?: number | undefined): Promise<import('./Track').TrackResults>;
    playlistOnce(id: string, offset?: number | undefined, length?: number | undefined): Promise<import("./api/AppleMusic").Playlist>;
    albumOnce(id: string, offset?: number | undefined, length?: number | undefined): Promise<import('./api/AppleMusic').Playlist>;
}
declare class Soundcloud extends APISource<"Soundcloud"> {
    constructor();
    match(content: string): null | {
        soundcloud: string;
    } | {
        shortlink: string;
    };
    resolve(match: ReturnType<typeof this.match>): Promise<import('./api/Soundcloud').Track | import('./api/Soundcloud').Playlist | null>;
    search(query: string, offset: number, length?: number | undefined): Promise<import('./Track').TrackResults>;
    playlistOnce(id: string, offset?: number | undefined, length?: number | undefined): Promise<import('./api/Soundcloud').Playlist | null>;
}
declare class Youtube extends APISource<"Youtube"> {
    constructor();
    Music: {
        innertube_client: {
            clientName: string;
            clientVersion: string;
            gl: string;
            hl: string;
        };
        innertube_key: string;
        readonly cookie: string;
        readonly sapisid: string;
        api_request(path: string, body?: {
            [key: string]: any;
        } | undefined, query?: string | undefined): Promise<{
            [key: string]: any;
        }>;
        search(search: string, continuation: any, params?: any): Promise<{
            [n: number]: any;
            process(body: any): void;
            process_section(section: any): void;
            top_result: any;
            songs: any[] | undefined;
            from_section(list: any[]): any[];
            process_once(body: any): void;
            extract_tracks(list: any): void;
            set_continuation(cont: any): void;
            continuation: any;
            set_browse(query: any, params: any): void;
            browse: any;
            query: any;
            next(): Promise<any | null>;
            length: number;
            toString(): string;
            toLocaleString(): string;
            pop(): any;
            push(...items: any[]): number;
            concat(...items: ConcatArray<any>[]): any[];
            concat(...items: any[]): any[];
            join(separator?: string | undefined): string;
            reverse(): any[];
            shift(): any;
            slice(start?: number | undefined, end?: number | undefined): any[];
            sort(compareFn?: ((a: any, b: any) => number) | undefined): any;
            splice(start: number, deleteCount?: number | undefined): any[];
            splice(start: number, deleteCount: number, ...items: any[]): any[];
            unshift(...items: any[]): number;
            indexOf(searchElement: any, fromIndex?: number | undefined): number;
            lastIndexOf(searchElement: any, fromIndex?: number | undefined): number;
            every<S extends any>(predicate: (value: any, index: number, array: any[]) => value is S, thisArg?: any): this is S[];
            every(predicate: (value: any, index: number, array: any[]) => unknown, thisArg?: any): boolean;
            some(predicate: (value: any, index: number, array: any[]) => unknown, thisArg?: any): boolean;
            forEach(callbackfn: (value: any, index: number, array: any[]) => void, thisArg?: any): void;
            map<U>(callbackfn: (value: any, index: number, array: any[]) => U, thisArg?: any): U[];
            filter<S_1 extends any>(predicate: (value: any, index: number, array: any[]) => value is S_1, thisArg?: any): S_1[];
            filter(predicate: (value: any, index: number, array: any[]) => unknown, thisArg?: any): any[];
            reduce(callbackfn: (previousValue: any, currentValue: any, currentIndex: number, array: any[]) => any): any;
            reduce(callbackfn: (previousValue: any, currentValue: any, currentIndex: number, array: any[]) => any, initialValue: any): any;
            reduce<U_1>(callbackfn: (previousValue: U_1, currentValue: any, currentIndex: number, array: any[]) => U_1, initialValue: U_1): U_1;
            reduceRight(callbackfn: (previousValue: any, currentValue: any, currentIndex: number, array: any[]) => any): any;
            reduceRight(callbackfn: (previousValue: any, currentValue: any, currentIndex: number, array: any[]) => any, initialValue: any): any;
            reduceRight<U_2>(callbackfn: (previousValue: U_2, currentValue: any, currentIndex: number, array: any[]) => U_2, initialValue: U_2): U_2;
            find<S_2 extends any>(predicate: (value: any, index: number, obj: any[]) => value is S_2, thisArg?: any): S_2 | undefined;
            find(predicate: (value: any, index: number, obj: any[]) => unknown, thisArg?: any): any;
            findIndex(predicate: (value: any, index: number, obj: any[]) => unknown, thisArg?: any): number;
            fill(value: any, start?: number | undefined, end?: number | undefined): any;
            copyWithin(target: number, start?: number | undefined, end?: number | undefined): any;
            entries(): IterableIterator<[number, any]>;
            keys(): IterableIterator<number>;
            values(): IterableIterator<any>;
            includes(searchElement: any, fromIndex?: number | undefined): boolean;
            flatMap<U_3, This = undefined>(callback: (this: This, value: any, index: number, array: any[]) => U_3 | readonly U_3[], thisArg?: This | undefined): U_3[];
            flat<A, D extends number = 1>(this: A, depth?: D | undefined): FlatArray<A, D>[];
            [Symbol.iterator](): IterableIterator<any>;
            readonly [Symbol.unscopables]: {
                [x: number]: boolean | undefined;
                length?: boolean | undefined;
                toString?: boolean | undefined;
                toLocaleString?: boolean | undefined;
                pop?: boolean | undefined;
                push?: boolean | undefined;
                concat?: boolean | undefined;
                join?: boolean | undefined;
                reverse?: boolean | undefined;
                shift?: boolean | undefined;
                slice?: boolean | undefined;
                sort?: boolean | undefined;
                splice?: boolean | undefined;
                unshift?: boolean | undefined;
                indexOf?: boolean | undefined;
                lastIndexOf?: boolean | undefined;
                every?: boolean | undefined;
                some?: boolean | undefined;
                forEach?: boolean | undefined;
                map?: boolean | undefined;
                filter?: boolean | undefined;
                reduce?: boolean | undefined;
                reduceRight?: boolean | undefined;
                find?: boolean | undefined;
                findIndex?: boolean | undefined;
                fill?: boolean | undefined;
                copyWithin?: boolean | undefined;
                entries?: boolean | undefined;
                keys?: boolean | undefined;
                values?: boolean | undefined;
                includes?: boolean | undefined;
                flatMap?: boolean | undefined;
                flat?: boolean | undefined;
                [Symbol.iterator]?: boolean | undefined;
                readonly [Symbol.unscopables]?: boolean | undefined;
                at?: boolean | undefined;
            };
            at(index: number): any;
        }>;
    };
    id_regex: RegExp;
    weak_match(id: string): {
        id: string;
    } | null;
    match(content: string): {
        id: string;
    } | {
        list: string;
    } | null;
    resolve(match: Exclude<ReturnType<Awaited<typeof this.match>>, null>): Promise<import('./api/Youtube').Track | import('./api/Youtube').Playlist>;
    weak_resolve(match: any): Promise<null | import('./api/Youtube').Track | import('./api/Youtube').Playlist>;
    override search(query: string, continuation?: unknown): Promise<import('./Track').TrackResults>;
    playlistOnce(id: string, start?: number | undefined): Promise<import('./api/Youtube').Playlist>;
    setCookie(cookie: string): void;
}
declare class File extends APISource<"File"> {
    constructor();
    resolve(content: string): Promise<ReturnType<typeof this.api.create> | null>;
}
declare class Spotify extends APISource<"Spotify"> {
    constructor();
    match(content: string): null | {
        track: string;
    } | {
        album: string;
    } | {
        playlist: string;
    };
    resolve(match: ReturnType<typeof this.match>): Promise<import('./api/Spotify').Track | import('./api/Spotify').Playlist | undefined>;
    search(query: string, offset?: number | undefined, length?: number | undefined): Promise<import('./Track').TrackResults>;
    playlistOnce(id: string, offset?: number | undefined, length?: number | undefined): Promise<import('./api/Spotify').Playlist>;
    albumOnce(id: string, offset?: number | undefined, length?: number | undefined): Promise<import('./api/Spotify').Playlist>;
    setCookie(cookie: string): void;
}
declare class APISource<T> {
    constructor(api: T);
    name: T;
    api: T extends 'AppleMusic' ? {
        Track: typeof import("./api/AppleMusic").Track;
        Results: typeof import("./api/AppleMusic").Results;
        Playlist: typeof import("./api/AppleMusic").Playlist;
        token: string | null;
        reloading: Promise<void> | null;
        needs_reload: boolean;
        reload(force?: boolean | undefined): Promise<void>;
        load(): Promise<void>;
        prefetch(): Promise<void> | undefined;
        api_request(path: string, query?: {
            [key: string]: any;
        } | undefined, options?: {
            [key: string]: any;
            headers?: {
                [key: string]: any;
                authorization?: string | undefined;
                origin?: string | undefined;
            } | undefined;
        } | undefined): Promise<any>;
        check_valid_id(id: string): void;
        get(id: string): Promise<import("./api/AppleMusic").Track>;
        get_streams(id: string): Promise<Promise<{
            [n: number]: any;
            expire: number | undefined;
            from(start: number, playerResponse: any): any;
            expired(): boolean;
            extract_streams(streams: any[], adaptive?: boolean | undefined): void;
            set(volume: number, live: any, time: number): void;
            volume: number | undefined;
            live: any;
            time: number | undefined;
            maybeExpired(): boolean;
            length: number;
            toString(): string;
            toLocaleString(): string;
            pop(): any;
            push(...items: any[]): number;
            concat(...items: ConcatArray<any>[]): any[];
            concat(...items: any[]): any[];
            join(separator?: string | undefined): string;
            reverse(): any[];
            shift(): any;
            slice(start?: number | undefined, end?: number | undefined): any[];
            sort(compareFn?: ((a: any, b: any) => number) | undefined): any;
            splice(start: number, deleteCount?: number | undefined): any[];
            splice(start: number, deleteCount: number, ...items: any[]): any[];
            unshift(...items: any[]): number;
            indexOf(searchElement: any, fromIndex?: number | undefined): number;
            lastIndexOf(searchElement: any, fromIndex?: number | undefined): number;
            every<S extends any>(predicate: (value: any, index: number, array: any[]) => value is S, thisArg?: any): this is S[];
            every(predicate: (value: any, index: number, array: any[]) => unknown, thisArg?: any): boolean;
            some(predicate: (value: any, index: number, array: any[]) => unknown, thisArg?: any): boolean;
            forEach(callbackfn: (value: any, index: number, array: any[]) => void, thisArg?: any): void;
            map<U>(callbackfn: (value: any, index: number, array: any[]) => U, thisArg?: any): U[];
            filter<S_1 extends any>(predicate: (value: any, index: number, array: any[]) => value is S_1, thisArg?: any): S_1[];
            filter(predicate: (value: any, index: number, array: any[]) => unknown, thisArg?: any): any[];
            reduce(callbackfn: (previousValue: any, currentValue: any, currentIndex: number, array: any[]) => any): any;
            reduce(callbackfn: (previousValue: any, currentValue: any, currentIndex: number, array: any[]) => any, initialValue: any): any;
            reduce<U_1>(callbackfn: (previousValue: U_1, currentValue: any, currentIndex: number, array: any[]) => U_1, initialValue: U_1): U_1;
            reduceRight(callbackfn: (previousValue: any, currentValue: any, currentIndex: number, array: any[]) => any): any;
            reduceRight(callbackfn: (previousValue: any, currentValue: any, currentIndex: number, array: any[]) => any, initialValue: any): any;
            reduceRight<U_2>(callbackfn: (previousValue: U_2, currentValue: any, currentIndex: number, array: any[]) => U_2, initialValue: U_2): U_2;
            find<S_2 extends any>(predicate: (value: any, index: number, obj: any[]) => value is S_2, thisArg?: any): S_2 | undefined;
            find(predicate: (value: any, index: number, obj: any[]) => unknown, thisArg?: any): any;
            findIndex(predicate: (value: any, index: number, obj: any[]) => unknown, thisArg?: any): number;
            fill(value: any, start?: number | undefined, end?: number | undefined): any;
            copyWithin(target: number, start?: number | undefined, end?: number | undefined): any;
            entries(): IterableIterator<[number, any]>;
            keys(): IterableIterator<number>;
            values(): IterableIterator<any>;
            includes(searchElement: any, fromIndex?: number | undefined): boolean;
            flatMap<U_3, This = undefined>(callback: (this: This, value: any, index: number, array: any[]) => U_3 | readonly U_3[], thisArg?: This | undefined): U_3[];
            flat<A, D extends number = 1>(this: A, depth?: D | undefined): FlatArray<A, D>[];
            [Symbol.iterator](): IterableIterator<any>;
            readonly [Symbol.unscopables]: {
                [x: number]: boolean | undefined;
                length?: boolean | undefined;
                toString?: boolean | undefined;
                toLocaleString?: boolean | undefined;
                pop?: boolean | undefined;
                push?: boolean | undefined;
                concat?: boolean | undefined;
                join?: boolean | undefined;
                reverse?: boolean | undefined;
                shift?: boolean | undefined;
                slice?: boolean | undefined;
                sort?: boolean | undefined;
                splice?: boolean | undefined;
                unshift?: boolean | undefined;
                indexOf?: boolean | undefined;
                lastIndexOf?: boolean | undefined;
                every?: boolean | undefined;
                some?: boolean | undefined;
                forEach?: boolean | undefined;
                map?: boolean | undefined;
                filter?: boolean | undefined;
                reduce?: boolean | undefined;
                reduceRight?: boolean | undefined;
                find?: boolean | undefined;
                findIndex?: boolean | undefined;
                fill?: boolean | undefined;
                copyWithin?: boolean | undefined;
                entries?: boolean | undefined;
                keys?: boolean | undefined;
                values?: boolean | undefined;
                includes?: boolean | undefined;
                flatMap?: boolean | undefined;
                flat?: boolean | undefined;
                [Symbol.iterator]?: boolean | undefined;
                readonly [Symbol.unscopables]?: boolean | undefined;
                at?: boolean | undefined;
            };
            at(index: number): any;
        }>>;
        get_next(url: string, param: any): number;
        search(query: any, offset?: number | undefined, limit?: number | undefined): Promise<import("./api/AppleMusic").Results>;
        list_once(type: string, id: string, offset?: number | undefined, limit?: number | undefined): Promise<import("./api/AppleMusic").Playlist>;
        check_valid_playlist_id(id: string): void;
        playlist_once(id: string, offset?: number | undefined, length?: number | undefined): Promise<import("./api/AppleMusic").Playlist>;
        album_once(id: string, offset?: number | undefined, length?: number | undefined): Promise<import("./api/AppleMusic").Playlist>;
        list(type: string, id: string, limit?: number | undefined): Promise<import("./api/AppleMusic").Playlist>;
        playlist(id: string, length?: number | undefined): Promise<import("./api/AppleMusic").Playlist>;
        album(id: string, length?: number | undefined): Promise<import("./api/AppleMusic").Playlist>;
    } : T extends 'File' ? {
        Track: typeof import("./api/File").Track;
        get(url: string): Promise<never>;
        get_streams(url: string): Promise<never>;
        playlist(url: string, length?: number | undefined): Promise<never>;
        create(url: string, isfile?: boolean | undefined): import("./api/File").Track;
    } : T extends 'Soundcloud' ? {
        Track: typeof import("./api/Soundcloud").Track;
        Results: typeof import("./api/Soundcloud").Results;
        Playlist: typeof import("./api/Soundcloud").Playlist;
        client_id: string | null;
        reloading: Promise<void> | null;
        reload(): Promise<void>;
        prefetch(): Promise<void>;
        load(): Promise<void>;
        request(path: string, query?: {
            [key: string]: string | null;
        } | undefined): Promise<any>;
        api_request(path: string, query?: {
            [key: string]: any;
        } | undefined): Promise<any>;
        resolve_playlist(list: {
            tracks: {
                id: string;
                streamable: boolean;
            }[];
            permalink_url: string;
            title: string;
            description: string;
            id: string;
        }, offset: number | undefined, limit: number): Promise<import("./api/Soundcloud").Playlist | null>;
        resolve(url: string): Promise<import("./api/Soundcloud").Track | import("./api/Soundcloud").Playlist | null>;
        resolve_shortlink(id: string): Promise<import("./api/Soundcloud").Track | import("./api/Soundcloud").Playlist | null>;
        check_valid_id(id: string): void;
        get(id: string): Promise<import("./api/Soundcloud").Track | import("./api/Soundcloud").Playlist | null>;
        get_streams(id: string): Promise<{
            [n: number]: any;
            from(track: {
                media: {
                    transcodings: {
                        format: {
                            mime_type: string;
                        };
                        url: string;
                        duration: number;
                    }[];
                };
            }): any;
            extract_streams(streams: {
                format: {
                    mime_type: string;
                };
                url: string;
                duration: number;
            }[]): void;
            expired(): boolean;
            maybeExpired(): boolean;
            set(volume: number, live: any, time: number): void;
            volume: number | undefined;
            live: any;
            time: number | undefined;
            length: number;
            toString(): string;
            toLocaleString(): string;
            pop(): any;
            push(...items: any[]): number;
            concat(...items: ConcatArray<any>[]): any[];
            concat(...items: any[]): any[];
            join(separator?: string | undefined): string;
            reverse(): any[];
            shift(): any;
            slice(start?: number | undefined, end?: number | undefined): any[];
            sort(compareFn?: ((a: any, b: any) => number) | undefined): any;
            splice(start: number, deleteCount?: number | undefined): any[];
            splice(start: number, deleteCount: number, ...items: any[]): any[];
            unshift(...items: any[]): number;
            indexOf(searchElement: any, fromIndex?: number | undefined): number;
            lastIndexOf(searchElement: any, fromIndex?: number | undefined): number;
            every<S_3 extends any>(predicate: (value: any, index: number, array: any[]) => value is S_3, thisArg?: any): this is S_3[];
            every(predicate: (value: any, index: number, array: any[]) => unknown, thisArg?: any): boolean;
            some(predicate: (value: any, index: number, array: any[]) => unknown, thisArg?: any): boolean;
            forEach(callbackfn: (value: any, index: number, array: any[]) => void, thisArg?: any): void;
            map<U_4>(callbackfn: (value: any, index: number, array: any[]) => U_4, thisArg?: any): U_4[];
            filter<S_4 extends any>(predicate: (value: any, index: number, array: any[]) => value is S_4, thisArg?: any): S_4[];
            filter(predicate: (value: any, index: number, array: any[]) => unknown, thisArg?: any): any[];
            reduce(callbackfn: (previousValue: any, currentValue: any, currentIndex: number, array: any[]) => any): any;
            reduce(callbackfn: (previousValue: any, currentValue: any, currentIndex: number, array: any[]) => any, initialValue: any): any;
            reduce<U_5>(callbackfn: (previousValue: U_5, currentValue: any, currentIndex: number, array: any[]) => U_5, initialValue: U_5): U_5;
            reduceRight(callbackfn: (previousValue: any, currentValue: any, currentIndex: number, array: any[]) => any): any;
            reduceRight(callbackfn: (previousValue: any, currentValue: any, currentIndex: number, array: any[]) => any, initialValue: any): any;
            reduceRight<U_6>(callbackfn: (previousValue: U_6, currentValue: any, currentIndex: number, array: any[]) => U_6, initialValue: U_6): U_6;
            find<S_5 extends any>(predicate: (value: any, index: number, obj: any[]) => value is S_5, thisArg?: any): S_5 | undefined;
            find(predicate: (value: any, index: number, obj: any[]) => unknown, thisArg?: any): any;
            findIndex(predicate: (value: any, index: number, obj: any[]) => unknown, thisArg?: any): number;
            fill(value: any, start?: number | undefined, end?: number | undefined): any;
            copyWithin(target: number, start?: number | undefined, end?: number | undefined): any;
            entries(): IterableIterator<[number, any]>;
            keys(): IterableIterator<number>;
            values(): IterableIterator<any>;
            includes(searchElement: any, fromIndex?: number | undefined): boolean;
            flatMap<U_7, This_1 = undefined>(callback: (this: This_1, value: any, index: number, array: any[]) => U_7 | readonly U_7[], thisArg?: This_1 | undefined): U_7[];
            flat<A_1, D_1 extends number = 1>(this: A_1, depth?: D_1 | undefined): FlatArray<A_1, D_1>[];
            [Symbol.iterator](): IterableIterator<any>;
            readonly [Symbol.unscopables]: {
                [x: number]: boolean | undefined;
                length?: boolean | undefined;
                toString?: boolean | undefined;
                toLocaleString?: boolean | undefined;
                pop?: boolean | undefined;
                push?: boolean | undefined;
                concat?: boolean | undefined;
                join?: boolean | undefined;
                reverse?: boolean | undefined;
                shift?: boolean | undefined;
                slice?: boolean | undefined;
                sort?: boolean | undefined;
                splice?: boolean | undefined;
                unshift?: boolean | undefined;
                indexOf?: boolean | undefined;
                lastIndexOf?: boolean | undefined;
                every?: boolean | undefined;
                some?: boolean | undefined;
                forEach?: boolean | undefined;
                map?: boolean | undefined;
                filter?: boolean | undefined;
                reduce?: boolean | undefined;
                reduceRight?: boolean | undefined;
                find?: boolean | undefined;
                findIndex?: boolean | undefined;
                fill?: boolean | undefined;
                copyWithin?: boolean | undefined;
                entries?: boolean | undefined;
                keys?: boolean | undefined;
                values?: boolean | undefined;
                includes?: boolean | undefined;
                flatMap?: boolean | undefined;
                flat?: boolean | undefined;
                [Symbol.iterator]?: boolean | undefined;
                readonly [Symbol.unscopables]?: boolean | undefined;
                at?: boolean | undefined;
            };
            at(index: number): any;
        }>;
        search(query: string, offset: number, limit?: number | undefined): Promise<import("./api/Soundcloud").Results>;
        playlist_once(id: string, offset?: number | undefined, limit?: number | undefined): Promise<import("./api/Soundcloud").Playlist | null>;
        playlist(id: string, limit?: number | undefined): Promise<import("./api/Soundcloud").Playlist | null>;
    } : T extends 'Spotify' ? {
        Track: typeof import("./api/Spotify").Track;
        Results: typeof import("./api/Spotify").Results;
        Playlist: typeof import("./api/Spotify").Playlist;
        token: string | null;
        reloading: Promise<void> | null;
        needs_reload: boolean;
        account_data: {};
        reload(force?: boolean | undefined): Promise<void>;
        load(): Promise<void>;
        prefetch(): Promise<void> | undefined;
        api_request(path: string, options?: import("node-fetch").RequestInit | undefined): Promise<{
            [key: string]: any;
        }>;
        check_valid_id(id: string): void;
        get(id: string): Promise<import("./api/Spotify").Track>;
        get_streams(id: string): Promise<{
            [n: number]: any;
            expire: number | undefined;
            from(start: number, playerResponse: any): any;
            expired(): boolean;
            extract_streams(streams: any[], adaptive?: boolean | undefined): void;
            set(volume: number, live: any, time: number): void;
            volume: number | undefined;
            live: any;
            time: number | undefined;
            maybeExpired(): boolean;
            length: number;
            toString(): string;
            toLocaleString(): string;
            pop(): any;
            push(...items: any[]): number;
            concat(...items: ConcatArray<any>[]): any[];
            concat(...items: any[]): any[];
            join(separator?: string | undefined): string;
            reverse(): any[];
            shift(): any;
            slice(start?: number | undefined, end?: number | undefined): any[];
            sort(compareFn?: ((a: any, b: any) => number) | undefined): any;
            splice(start: number, deleteCount?: number | undefined): any[];
            splice(start: number, deleteCount: number, ...items: any[]): any[];
            unshift(...items: any[]): number;
            indexOf(searchElement: any, fromIndex?: number | undefined): number;
            lastIndexOf(searchElement: any, fromIndex?: number | undefined): number;
            every<S extends any>(predicate: (value: any, index: number, array: any[]) => value is S, thisArg?: any): this is S[];
            every(predicate: (value: any, index: number, array: any[]) => unknown, thisArg?: any): boolean;
            some(predicate: (value: any, index: number, array: any[]) => unknown, thisArg?: any): boolean;
            forEach(callbackfn: (value: any, index: number, array: any[]) => void, thisArg?: any): void;
            map<U>(callbackfn: (value: any, index: number, array: any[]) => U, thisArg?: any): U[];
            filter<S_1 extends any>(predicate: (value: any, index: number, array: any[]) => value is S_1, thisArg?: any): S_1[];
            filter(predicate: (value: any, index: number, array: any[]) => unknown, thisArg?: any): any[];
            reduce(callbackfn: (previousValue: any, currentValue: any, currentIndex: number, array: any[]) => any): any;
            reduce(callbackfn: (previousValue: any, currentValue: any, currentIndex: number, array: any[]) => any, initialValue: any): any;
            reduce<U_1>(callbackfn: (previousValue: U_1, currentValue: any, currentIndex: number, array: any[]) => U_1, initialValue: U_1): U_1;
            reduceRight(callbackfn: (previousValue: any, currentValue: any, currentIndex: number, array: any[]) => any): any;
            reduceRight(callbackfn: (previousValue: any, currentValue: any, currentIndex: number, array: any[]) => any, initialValue: any): any;
            reduceRight<U_2>(callbackfn: (previousValue: U_2, currentValue: any, currentIndex: number, array: any[]) => U_2, initialValue: U_2): U_2;
            find<S_2 extends any>(predicate: (value: any, index: number, obj: any[]) => value is S_2, thisArg?: any): S_2 | undefined;
            find(predicate: (value: any, index: number, obj: any[]) => unknown, thisArg?: any): any;
            findIndex(predicate: (value: any, index: number, obj: any[]) => unknown, thisArg?: any): number;
            fill(value: any, start?: number | undefined, end?: number | undefined): any;
            copyWithin(target: number, start?: number | undefined, end?: number | undefined): any;
            entries(): IterableIterator<[number, any]>;
            keys(): IterableIterator<number>;
            values(): IterableIterator<any>;
            includes(searchElement: any, fromIndex?: number | undefined): boolean;
            flatMap<U_3, This = undefined>(callback: (this: This, value: any, index: number, array: any[]) => U_3 | readonly U_3[], thisArg?: This | undefined): U_3[];
            flat<A, D extends number = 1>(this: A, depth?: D | undefined): FlatArray<A, D>[];
            [Symbol.iterator](): IterableIterator<any>;
            readonly [Symbol.unscopables]: {
                [x: number]: boolean | undefined;
                length?: boolean | undefined;
                toString?: boolean | undefined;
                toLocaleString?: boolean | undefined;
                pop?: boolean | undefined;
                push?: boolean | undefined;
                concat?: boolean | undefined;
                join?: boolean | undefined;
                reverse?: boolean | undefined;
                shift?: boolean | undefined;
                slice?: boolean | undefined;
                sort?: boolean | undefined;
                splice?: boolean | undefined;
                unshift?: boolean | undefined;
                indexOf?: boolean | undefined;
                lastIndexOf?: boolean | undefined;
                every?: boolean | undefined;
                some?: boolean | undefined;
                forEach?: boolean | undefined;
                map?: boolean | undefined;
                filter?: boolean | undefined;
                reduce?: boolean | undefined;
                reduceRight?: boolean | undefined;
                find?: boolean | undefined;
                findIndex?: boolean | undefined;
                fill?: boolean | undefined;
                copyWithin?: boolean | undefined;
                entries?: boolean | undefined;
                keys?: boolean | undefined;
                values?: boolean | undefined;
                includes?: boolean | undefined;
                flatMap?: boolean | undefined;
                flat?: boolean | undefined;
                [Symbol.iterator]?: boolean | undefined;
                readonly [Symbol.unscopables]?: boolean | undefined;
                at?: boolean | undefined;
            };
            at(index: number): any;
        }>;
        search(query: string, start?: number | undefined, length?: number | undefined): Promise<import("./api/Spotify").Results>;
        list_once(type: "playlists" | "albums", id: string, start?: number | undefined, length?: number | undefined): Promise<import("./api/Spotify").Playlist>;
        playlist_once(id: string, start?: number | undefined, length?: number | undefined): Promise<import("./api/Spotify").Playlist>;
        album_once(id: string, start?: number | undefined, length?: number | undefined): Promise<import("./api/Spotify").Playlist>;
        list(type: any, id: string, limit?: number | undefined): Promise<import("./api/Spotify").Playlist>;
        playlist(id: string, length?: number | undefined): Promise<import("./api/Spotify").Playlist>;
        album(id: string, length?: number | undefined): Promise<import("./api/Spotify").Playlist>;
        set_cookie(cookie: string): void;
    } : {
        Track: typeof import("./api/Youtube").Track;
        Results: typeof import("./api/Youtube").Results;
        Playlist: typeof import("./api/Youtube").Playlist;
        Music: {
            innertube_client: {
                clientName: string;
                clientVersion: string;
                gl: string;
                hl: string;
            };
            innertube_key: string;
            readonly cookie: string;
            readonly sapisid: string;
            api_request(path: string, body?: {
                [key: string]: any;
            } | undefined, query?: string | undefined): Promise<{
                [key: string]: any;
            }>;
            search(search: string, continuation: any, params?: any): Promise<{
                [n: number]: any;
                process(body: any): void;
                process_section(section: any): void;
                top_result: any;
                songs: any[] | undefined;
                from_section(list: any[]): any[];
                process_once(body: any): void;
                extract_tracks(list: any): void;
                set_continuation(cont: any): void;
                continuation: any;
                set_browse(query: any, params: any): void;
                browse: any;
                query: any;
                next(): Promise<any | null>;
                length: number;
                toString(): string;
                toLocaleString(): string;
                pop(): any;
                push(...items: any[]): number;
                concat(...items: ConcatArray<any>[]): any[];
                concat(...items: any[]): any[];
                join(separator?: string | undefined): string;
                reverse(): any[];
                shift(): any;
                slice(start?: number | undefined, end?: number | undefined): any[];
                sort(compareFn?: ((a: any, b: any) => number) | undefined): any;
                splice(start: number, deleteCount?: number | undefined): any[];
                splice(start: number, deleteCount: number, ...items: any[]): any[];
                unshift(...items: any[]): number;
                indexOf(searchElement: any, fromIndex?: number | undefined): number;
                lastIndexOf(searchElement: any, fromIndex?: number | undefined): number;
                every<S_6 extends any>(predicate: (value: any, index: number, array: any[]) => value is S_6, thisArg?: any): this is S_6[];
                every(predicate: (value: any, index: number, array: any[]) => unknown, thisArg?: any): boolean;
                some(predicate: (value: any, index: number, array: any[]) => unknown, thisArg?: any): boolean;
                forEach(callbackfn: (value: any, index: number, array: any[]) => void, thisArg?: any): void;
                map<U_8>(callbackfn: (value: any, index: number, array: any[]) => U_8, thisArg?: any): U_8[];
                filter<S_7 extends any>(predicate: (value: any, index: number, array: any[]) => value is S_7, thisArg?: any): S_7[];
                filter(predicate: (value: any, index: number, array: any[]) => unknown, thisArg?: any): any[];
                reduce(callbackfn: (previousValue: any, currentValue: any, currentIndex: number, array: any[]) => any): any;
                reduce(callbackfn: (previousValue: any, currentValue: any, currentIndex: number, array: any[]) => any, initialValue: any): any;
                reduce<U_9>(callbackfn: (previousValue: U_9, currentValue: any, currentIndex: number, array: any[]) => U_9, initialValue: U_9): U_9;
                reduceRight(callbackfn: (previousValue: any, currentValue: any, currentIndex: number, array: any[]) => any): any;
                reduceRight(callbackfn: (previousValue: any, currentValue: any, currentIndex: number, array: any[]) => any, initialValue: any): any;
                reduceRight<U_10>(callbackfn: (previousValue: U_10, currentValue: any, currentIndex: number, array: any[]) => U_10, initialValue: U_10): U_10;
                find<S_8 extends any>(predicate: (value: any, index: number, obj: any[]) => value is S_8, thisArg?: any): S_8 | undefined;
                find(predicate: (value: any, index: number, obj: any[]) => unknown, thisArg?: any): any;
                findIndex(predicate: (value: any, index: number, obj: any[]) => unknown, thisArg?: any): number;
                fill(value: any, start?: number | undefined, end?: number | undefined): any;
                copyWithin(target: number, start?: number | undefined, end?: number | undefined): any;
                entries(): IterableIterator<[number, any]>;
                keys(): IterableIterator<number>;
                values(): IterableIterator<any>;
                includes(searchElement: any, fromIndex?: number | undefined): boolean;
                flatMap<U_11, This_2 = undefined>(callback: (this: This_2, value: any, index: number, array: any[]) => U_11 | readonly U_11[], thisArg?: This_2 | undefined): U_11[];
                flat<A_2, D_2 extends number = 1>(this: A_2, depth?: D_2 | undefined): FlatArray<A_2, D_2>[];
                [Symbol.iterator](): IterableIterator<any>;
                readonly [Symbol.unscopables]: {
                    [x: number]: boolean | undefined;
                    length?: boolean | undefined;
                    toString?: boolean | undefined;
                    toLocaleString?: boolean | undefined;
                    pop?: boolean | undefined;
                    push?: boolean | undefined;
                    concat?: boolean | undefined;
                    join?: boolean | undefined;
                    reverse?: boolean | undefined;
                    shift?: boolean | undefined;
                    slice?: boolean | undefined;
                    sort?: boolean | undefined;
                    splice?: boolean | undefined;
                    unshift?: boolean | undefined;
                    indexOf?: boolean | undefined;
                    lastIndexOf?: boolean | undefined;
                    every?: boolean | undefined;
                    some?: boolean | undefined;
                    forEach?: boolean | undefined;
                    map?: boolean | undefined;
                    filter?: boolean | undefined;
                    reduce?: boolean | undefined;
                    reduceRight?: boolean | undefined;
                    find?: boolean | undefined;
                    findIndex?: boolean | undefined;
                    fill?: boolean | undefined;
                    copyWithin?: boolean | undefined;
                    entries?: boolean | undefined;
                    keys?: boolean | undefined;
                    values?: boolean | undefined;
                    includes?: boolean | undefined;
                    flatMap?: boolean | undefined;
                    flat?: boolean | undefined;
                    [Symbol.iterator]?: boolean | undefined;
                    readonly [Symbol.unscopables]?: boolean | undefined;
                    at?: boolean | undefined;
                };
                at(index: number): any;
            }>;
        };
        innertube_client: {
            clientName: string;
            clientVersion: string;
            gl: string;
            hl: string;
        };
        innertube_key: string;
        cookie: string;
        sapisid: string;
        api_request(path: string, body?: {
            [key: string]: any;
        } | undefined, query?: string | undefined, origin?: string | undefined): Promise<{
            [key: string]: any;
        }>;
        get(id: string): Promise<import("./api/Youtube").Track>;
        get_streams(id: string): Promise<{
            [n: number]: any;
            expire: number | undefined;
            from(start: number, playerResponse: any): any;
            expired(): boolean;
            extract_streams(streams: any[], adaptive?: boolean | undefined): void;
            set(volume: number, live: any, time: number): void;
            volume: number | undefined;
            live: any;
            time: number | undefined;
            maybeExpired(): boolean;
            length: number;
            toString(): string;
            toLocaleString(): string;
            pop(): any;
            push(...items: any[]): number;
            concat(...items: ConcatArray<any>[]): any[];
            concat(...items: any[]): any[];
            join(separator?: string | undefined): string;
            reverse(): any[];
            shift(): any;
            slice(start?: number | undefined, end?: number | undefined): any[];
            sort(compareFn?: ((a: any, b: any) => number) | undefined): any;
            splice(start: number, deleteCount?: number | undefined): any[];
            splice(start: number, deleteCount: number, ...items: any[]): any[];
            unshift(...items: any[]): number;
            indexOf(searchElement: any, fromIndex?: number | undefined): number;
            lastIndexOf(searchElement: any, fromIndex?: number | undefined): number;
            every<S extends any>(predicate: (value: any, index: number, array: any[]) => value is S, thisArg?: any): this is S[];
            every(predicate: (value: any, index: number, array: any[]) => unknown, thisArg?: any): boolean;
            some(predicate: (value: any, index: number, array: any[]) => unknown, thisArg?: any): boolean;
            forEach(callbackfn: (value: any, index: number, array: any[]) => void, thisArg?: any): void;
            map<U>(callbackfn: (value: any, index: number, array: any[]) => U, thisArg?: any): U[];
            filter<S_1 extends any>(predicate: (value: any, index: number, array: any[]) => value is S_1, thisArg?: any): S_1[];
            filter(predicate: (value: any, index: number, array: any[]) => unknown, thisArg?: any): any[];
            reduce(callbackfn: (previousValue: any, currentValue: any, currentIndex: number, array: any[]) => any): any;
            reduce(callbackfn: (previousValue: any, currentValue: any, currentIndex: number, array: any[]) => any, initialValue: any): any;
            reduce<U_1>(callbackfn: (previousValue: U_1, currentValue: any, currentIndex: number, array: any[]) => U_1, initialValue: U_1): U_1;
            reduceRight(callbackfn: (previousValue: any, currentValue: any, currentIndex: number, array: any[]) => any): any;
            reduceRight(callbackfn: (previousValue: any, currentValue: any, currentIndex: number, array: any[]) => any, initialValue: any): any;
            reduceRight<U_2>(callbackfn: (previousValue: U_2, currentValue: any, currentIndex: number, array: any[]) => U_2, initialValue: U_2): U_2;
            find<S_2 extends any>(predicate: (value: any, index: number, obj: any[]) => value is S_2, thisArg?: any): S_2 | undefined;
            find(predicate: (value: any, index: number, obj: any[]) => unknown, thisArg?: any): any;
            findIndex(predicate: (value: any, index: number, obj: any[]) => unknown, thisArg?: any): number;
            fill(value: any, start?: number | undefined, end?: number | undefined): any;
            copyWithin(target: number, start?: number | undefined, end?: number | undefined): any;
            entries(): IterableIterator<[number, any]>;
            keys(): IterableIterator<number>;
            values(): IterableIterator<any>;
            includes(searchElement: any, fromIndex?: number | undefined): boolean;
            flatMap<U_3, This = undefined>(callback: (this: This, value: any, index: number, array: any[]) => U_3 | readonly U_3[], thisArg?: This | undefined): U_3[];
            flat<A, D extends number = 1>(this: A, depth?: D | undefined): FlatArray<A, D>[];
            [Symbol.iterator](): IterableIterator<any>;
            readonly [Symbol.unscopables]: {
                [x: number]: boolean | undefined;
                length?: boolean | undefined;
                toString?: boolean | undefined;
                toLocaleString?: boolean | undefined;
                pop?: boolean | undefined;
                push?: boolean | undefined;
                concat?: boolean | undefined;
                join?: boolean | undefined;
                reverse?: boolean | undefined;
                shift?: boolean | undefined;
                slice?: boolean | undefined;
                sort?: boolean | undefined;
                splice?: boolean | undefined;
                unshift?: boolean | undefined;
                indexOf?: boolean | undefined;
                lastIndexOf?: boolean | undefined;
                every?: boolean | undefined;
                some?: boolean | undefined;
                forEach?: boolean | undefined;
                map?: boolean | undefined;
                filter?: boolean | undefined;
                reduce?: boolean | undefined;
                reduceRight?: boolean | undefined;
                find?: boolean | undefined;
                findIndex?: boolean | undefined;
                fill?: boolean | undefined;
                copyWithin?: boolean | undefined;
                entries?: boolean | undefined;
                keys?: boolean | undefined;
                values?: boolean | undefined;
                includes?: boolean | undefined;
                flatMap?: boolean | undefined;
                flat?: boolean | undefined;
                [Symbol.iterator]?: boolean | undefined;
                readonly [Symbol.unscopables]?: boolean | undefined;
                at?: boolean | undefined;
            };
            at(index: number): any;
        }>;
        playlist_once(id: string, start?: number | undefined): Promise<import("./api/Youtube").Playlist>;
        playlist(id: string, limit?: number | undefined): Promise<import("./api/Youtube").Playlist>;
        search(query: unknown, continuation?: unknown): Promise<import("./api/Youtube").Results>;
        set_cookie(cookiestr: string): void;
        string_word_match(big: string, small: string): number;
        track_match_score(track: any, result: any): number;
        track_match_best(results: any, track: any): any;
        track_match_best_result(results: any, track: any): any;
        track_match_lookup(track: any): Promise<any>;
        track_match(track: any): Promise<{
            [n: number]: any;
            expire: number | undefined;
            from(start: number, playerResponse: any): any;
            expired(): boolean;
            extract_streams(streams: any[], adaptive?: boolean | undefined): void;
            set(volume: number, live: any, time: number): void;
            volume: number | undefined;
            live: any;
            time: number | undefined;
            maybeExpired(): boolean;
            length: number;
            toString(): string;
            toLocaleString(): string;
            pop(): any;
            push(...items: any[]): number;
            concat(...items: ConcatArray<any>[]): any[];
            concat(...items: any[]): any[];
            join(separator?: string | undefined): string;
            reverse(): any[];
            shift(): any;
            slice(start?: number | undefined, end?: number | undefined): any[];
            sort(compareFn?: ((a: any, b: any) => number) | undefined): any;
            splice(start: number, deleteCount?: number | undefined): any[];
            splice(start: number, deleteCount: number, ...items: any[]): any[];
            unshift(...items: any[]): number;
            indexOf(searchElement: any, fromIndex?: number | undefined): number;
            lastIndexOf(searchElement: any, fromIndex?: number | undefined): number;
            every<S extends any>(predicate: (value: any, index: number, array: any[]) => value is S, thisArg?: any): this is S[];
            every(predicate: (value: any, index: number, array: any[]) => unknown, thisArg?: any): boolean;
            some(predicate: (value: any, index: number, array: any[]) => unknown, thisArg?: any): boolean;
            forEach(callbackfn: (value: any, index: number, array: any[]) => void, thisArg?: any): void;
            map<U>(callbackfn: (value: any, index: number, array: any[]) => U, thisArg?: any): U[];
            filter<S_1 extends any>(predicate: (value: any, index: number, array: any[]) => value is S_1, thisArg?: any): S_1[];
            filter(predicate: (value: any, index: number, array: any[]) => unknown, thisArg?: any): any[];
            reduce(callbackfn: (previousValue: any, currentValue: any, currentIndex: number, array: any[]) => any): any;
            reduce(callbackfn: (previousValue: any, currentValue: any, currentIndex: number, array: any[]) => any, initialValue: any): any;
            reduce<U_1>(callbackfn: (previousValue: U_1, currentValue: any, currentIndex: number, array: any[]) => U_1, initialValue: U_1): U_1;
            reduceRight(callbackfn: (previousValue: any, currentValue: any, currentIndex: number, array: any[]) => any): any;
            reduceRight(callbackfn: (previousValue: any, currentValue: any, currentIndex: number, array: any[]) => any, initialValue: any): any;
            reduceRight<U_2>(callbackfn: (previousValue: U_2, currentValue: any, currentIndex: number, array: any[]) => U_2, initialValue: U_2): U_2;
            find<S_2 extends any>(predicate: (value: any, index: number, obj: any[]) => value is S_2, thisArg?: any): S_2 | undefined;
            find(predicate: (value: any, index: number, obj: any[]) => unknown, thisArg?: any): any;
            findIndex(predicate: (value: any, index: number, obj: any[]) => unknown, thisArg?: any): number;
            fill(value: any, start?: number | undefined, end?: number | undefined): any;
            copyWithin(target: number, start?: number | undefined, end?: number | undefined): any;
            entries(): IterableIterator<[number, any]>;
            keys(): IterableIterator<number>;
            values(): IterableIterator<any>;
            includes(searchElement: any, fromIndex?: number | undefined): boolean;
            flatMap<U_3, This = undefined>(callback: (this: This, value: any, index: number, array: any[]) => U_3 | readonly U_3[], thisArg?: This | undefined): U_3[];
            flat<A, D extends number = 1>(this: A, depth?: D | undefined): FlatArray<A, D>[];
            [Symbol.iterator](): IterableIterator<any>;
            readonly [Symbol.unscopables]: {
                [x: number]: boolean | undefined;
                length?: boolean | undefined;
                toString?: boolean | undefined;
                toLocaleString?: boolean | undefined;
                pop?: boolean | undefined;
                push?: boolean | undefined;
                concat?: boolean | undefined;
                join?: boolean | undefined;
                reverse?: boolean | undefined;
                shift?: boolean | undefined;
                slice?: boolean | undefined;
                sort?: boolean | undefined;
                splice?: boolean | undefined;
                unshift?: boolean | undefined;
                indexOf?: boolean | undefined;
                lastIndexOf?: boolean | undefined;
                every?: boolean | undefined;
                some?: boolean | undefined;
                forEach?: boolean | undefined;
                map?: boolean | undefined;
                filter?: boolean | undefined;
                reduce?: boolean | undefined;
                reduceRight?: boolean | undefined;
                find?: boolean | undefined;
                findIndex?: boolean | undefined;
                fill?: boolean | undefined;
                copyWithin?: boolean | undefined;
                entries?: boolean | undefined;
                keys?: boolean | undefined;
                values?: boolean | undefined;
                includes?: boolean | undefined;
                flatMap?: boolean | undefined;
                flat?: boolean | undefined;
                [Symbol.iterator]?: boolean | undefined;
                readonly [Symbol.unscopables]?: boolean | undefined;
                at?: boolean | undefined;
            };
            at(index: number): any;
        }>;
    };
    Track: T extends 'AppleMusic' ? import('./api/AppleMusic').Track : T extends 'File' ? undefined : T extends 'Soundcloud' ? typeof import('./api/Soundcloud').Track : T extends 'Spotify' ? typeof import('./api/Spotify').Track : typeof import('./api/Youtube').Track;
    Results: T extends 'AppleMusic' ? import('./api/AppleMusic').Results : T extends 'File' ? undefined : T extends 'Soundcloud' ? typeof import('./api/Soundcloud').Results : T extends 'Spotify' ? typeof import('./api/Spotify').Results : typeof import('./api/Youtube').Results;
    Playlist: T extends 'AppleMusic' ? import('./api/AppleMusic').Playlist : T extends 'File' ? undefined : T extends 'Soundcloud' ? typeof import('./api/Soundcloud').Playlist : T extends 'Spotify' ? typeof import('./api/Spotify').Playlist : typeof import('./api/Youtube').Playlist;
    match(content: string): any;
    weak_match(content: any): any;
    matches(content: any): boolean;
    resolve(match: any): Promise<any>;
    get(id: string): Promise<ReturnType<typeof this.api.get>>;
    getStreams(id: string): Promise<ReturnType<typeof this.api.get_streams>>;
    search(query: string): Promise<any>;
    playlistOnce(id: string): Promise<any>;
    playlist(id: string, length?: number | undefined): Promise<ReturnType<typeof this.api.playlist>>;
}
